# Generated by Django 5.1.3 on 2024-11-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='precio_por_noche',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='capacidad',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='orientacion',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
