# Generated by Django 5.1.3 on 2024-11-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_habitacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('simple', 'Simple'), ('doble', 'Doble'), ('triple', 'Triple')], max_length=50),
        ),
    ]
