# Generated by Django 5.1.3 on 2024-11-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_habitacion_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huesped',
            old_name='rut',
            new_name='num_documento',
        ),
        migrations.AddField(
            model_name='huesped',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='huesped',
            name='pais',
            field=models.CharField(default='chile', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='huesped',
            name='tipo_documento',
            field=models.CharField(default='rut', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No disponible')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='stok',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
