# Generated by Django 5.1.3 on 2024-12-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_huesped_hotel_producto_hotel_reserva_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
