# Generated by Django 5.1.3 on 2024-12-07 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_habitacion_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('adelanto', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_pago', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_checkin',
            new_name='fecha_entrada',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_checkout',
            new_name='fecha_salida',
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='gestion.pago'),
            preserve_default=False,
        ),
    ]
