# Generated by Django 5.1.3 on 2024-12-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_pago_rename_fecha_checkin_reserva_fecha_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
