# Generated by Django 5.1.3 on 2024-12-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_habitacion_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='saldo_restante',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
